# Generated by Django 2.2.5 on 2021-03-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='PseudoAcc',
            field=models.CharField(max_length=6),
        ),
    ]
